### ISSUE TITLE
Identic shortkey on multiple URLs

### ISSUE THREAD

**Issue by snemias** [behnamazimi/in-site-shorteys#2]
Hi Behnam

Great work.

I'd like the same keyboard shortcuts on my daily drivers. E.g. deleting mails and todos in a) Mails in Google Workspace and b) Todoist. Both web apps change the URL for almost every view. This makes it complicated with "Add Click Shortkey" - every view requires a new shortkey. Is this correct? If yes, this would be my #1 RFC.

More details what complicate means:

1) I'd like to use DEL (this is "fn" + "backspace" on a Macbook Air M1 with SWISS LAYOUT). To achieve this you need to add a "Click Shortkey" for every view in Google Workspace Mails. This means every "folder" (inbox, sent, archive, ...). Doable, but a pain.

 2) I can use one Keyboard Shortcut (in my case "fn" + "backspace" as explained before) just once. This is a show stopper.

Cheers
Simon

**Comment by behnamazimi** [comment]
Hey @snemias 
What you mentioned is not a case,  After adding a shortcut it would be valid through the whole domain not only one URL. 
For example: if you add a shortcut for `keep.google.com/u/0` it will also work on `keep.google.com/u/1`.

Please make sure that the main domain is not changing. If it's like you said anyway, share the platform name with me so I can debug it specifically.
