### ISSUE TITLE
Combination of "COMMAND" + "BACKSPACE" on macOS

### ISSUE THREAD

**Issue by snemias** [behnamazimi/in-site-shorteys#4]
Hi

The combination of "COMMAND" + "BACKSPACE" on macOS is accepted. In most cases a push of "COMMAND" later already triggers the action. Seems like a buk, doesn't it?

BTW it says in the windows "META" + ...

Cheers
Simon

**Comment by behnamazimi** [comment]
Hey @snemias
I was not able to simulate the case and it works on my device. could you give some extra details, e.g which website it is?
