### ISSUE TITLE
Setting "Prevent ... when focused on an input" should be defined on a individual shortkey base

### ISSUE THREAD

**Issue by snemias** [behnamazimi/in-site-shorteys#5]
Now it is defined globally.

Cheers 
Simon

**Comment by behnamazimi** [comment]
@snemias thank you for all your reports and feedback. Since I have some work on my agenda so it would take some time to fix them all or add some features. I'll take care of them ASAP.

**Comment by snemias** [comment]
Thanks.

**Comment by snemias** [comment]
> @snemias thank you for all your reports and feedback. Since I have some work on my agenda so it would take some time to fix them all or add some features. I'll take care of them ASAP.

maybe you could give me in the meantime a hint, what you mean with script. Is it javascript?

**Comment by behnamazimi** [comment]
According to the new policies, it is not possible to add any third-party scripts to the content. 
Before that, all kinds of scripts were allowed to inject and run on the content of a website. In this case, I should remove the script shortcut functionality. @snemias

**Comment by snemias** [comment]
I see. Thanks for clarification.

**Comment by behnamazimi** [comment]
Hey @snemias 
Prevent if focused on an input choose added for individual shortcuts too. and will be published soon. 
v1.7
